<?php

// This file is automatically generated for synchronization between development and production.
// Created: 2026-07-21 21:34:32

return array (
  0 => 
  array (
    'id' => '12',
    'version' => '1.2.6',
    'release_date' => '2026-07-20',
    'description' => 'Perbaikan bug filter kelas berdasarkan tahun ajaran aktif pada akun guru
Perbaikan perhitungan absensi pada periode tahun ajaran aktif
Perbaikan logika perhitungan jam pelajaran guru dengan satu jam pelajaran = 35-40 menit
Perbaikan tampilan tabel ATP
Perbaikan tampilan dashboard guru
Perbaikan tampilan hasil tracking nilai pada siswa yang lulus
Penambahan fitur Update Online (OTA)

',
    'is_stable' => '1',
    'created_at' => '2026-07-20 20:01:51',
    'updated_at' => '2026-07-21 21:34:32',
  ),
  1 => 
  array (
    'id' => '11',
    'version' => '1.2.5',
    'release_date' => '2026-07-11',
    'description' => 'Perbaikan logika penempatan siswa
Perbaikan logika kenaikan dan kelulusan
Perbaikan logika data riwayat siswa
Perbaikan bug tahun ajaran aktif
',
    'is_stable' => '0',
    'created_at' => '2026-07-11 01:25:33',
    'updated_at' => '2026-07-20 20:01:58',
  ),
  2 => 
  array (
    'id' => '10',
    'version' => '1.2.4',
    'release_date' => '2026-06-30',
    'description' => 'Penambahan Fitur Absensi Guru untuk kepentingan sekolah swasta yang menghitung kehadiran berdasarkan jam tatap muka guru
Perbaikan berbagi ATP untuk pelajaran dan level yang sama
Perbaikan rubrik dan komponen pada Kokurikuler dengan pemilihan jenis kegiatan lainnya
Perbaikan halaman pembuatan Jurnal Mengajar
Penambahan fitur maonitoring Administrasi guru bagi Kepala Sekolah',
    'is_stable' => '0',
    'created_at' => '2026-06-30 22:40:25',
    'updated_at' => '2026-07-11 01:25:42',
  ),
  3 => 
  array (
    'id' => '9',
    'version' => '1.2.3',
    'release_date' => '2026-06-16',
    'description' => 'Perubahan struktur logika pembuatan Analisis Tujuan Pembelajaran
Penambahan fitur Buku Tamu dengan QR Code
Penambahan Administrasi Surat Masuk dan Keluar',
    'is_stable' => '0',
    'created_at' => '2026-06-16 14:27:17',
    'updated_at' => '2026-07-11 01:21:17',
  ),
  4 => 
  array (
    'id' => '8',
    'version' => '1.2.2',
    'release_date' => '2026-05-15',
    'description' => 'Penambahan Fitur Chatroom Guru
Perubahan Struktur Nilai Raport dengan penambahan erapor
Perbaikan absensi mingguan
Perbaikan beberapa bug cetak dan ekspor PDF
',
    'is_stable' => '0',
    'created_at' => '2026-05-15 07:57:21',
    'updated_at' => '2026-06-16 14:27:33',
  ),
  5 => 
  array (
    'id' => '7',
    'version' => '1.2.1',
    'release_date' => '2026-04-18',
    'description' => 'Penambahan Fitur Kokurikuler yang ditangani oleh admin/ wali kelas terdiri dari Perencanaan, Pelaksanaan, Penilaian dan Pelaporan
Penambahan Fitur Saling Sharing Perencanaan Kokurikuler dalam satu Level atau Fase
Update Pelaporan Rekapitulasi Nilai untuk per jenis penilaian per kelas',
    'is_stable' => '0',
    'created_at' => '2026-04-18 12:23:11',
    'updated_at' => '2026-06-16 14:27:26',
  ),
  6 => 
  array (
    'id' => '6',
    'version' => '1.2.0',
    'release_date' => '2026-04-04',
    'description' => 'Penambahan fitur tarik data siswa dan guru dari Dapodik untuk lingkungan kerja satu jaringan atau melalui Push PowerShell jika SIKAP terpasang online 
Penambahan fitur Administrasi guru yang memungkinkan guru menyususn administrasinya secara digital
Pemanfaatan penggunaan AI untuk menggenerate Modul Ajar pada Administrasi Guru
Perubahan penggunaan Materi sebagai dasar penilaian menjadi Tujuan Pembelajaran di ATP
Penambahan fitur Jurnal Mengajar sebagai catatan proses pembelajaran guru di kelas
Penambahan fitur Jadwal Pelajaran
',
    'is_stable' => '0',
    'created_at' => '2026-04-04 22:30:47',
    'updated_at' => '2026-04-18 12:23:21',
  ),
  7 => 
  array (
    'id' => '5',
    'version' => '1.1.4',
    'release_date' => '2026-02-20',
    'description' => 'Optimasi query dan indexing database modul CBT
Efesiensi motode ping dan cahing modul CBT
Penambahan kompresi respon dan perbaikan auto save di pengerjaan soal
Perbaikan logika penilaian berdasarkan soal yang tampil
Perbaikan anti cheat untuk lebih informatif 
Pergantian teks editor dari tinyMCE ke CKEditor
Penambahan anti translate untuk ujian bahasa
Perbaikan tampilan tab halaman admin
Dynamic version display from database 
Penambahan CSRF protection di semua form
Keharusan update password default bagi pengguna
',
    'is_stable' => '0',
    'created_at' => '2026-02-20 22:38:33',
    'updated_at' => '2026-04-04 22:31:01',
  ),
  8 => 
  array (
    'id' => '4',
    'version' => '1.1.3',
    'release_date' => '2026-02-20',
    'description' => 'Pembatasan penggunaan aplikasi dengan lisensi langganan
Penambahan menu cetak kartu sekaligus jadwal ujian di CBT
Penambahan menu Daftar Hadir di CBT
Penambahan tipe soal Pilihan Ganda Kompleks dan soal Benar Salah di CBT ',
    'is_stable' => '0',
    'created_at' => '2026-02-19 11:46:42',
    'updated_at' => '2026-02-20 22:38:39',
  ),
  9 => 
  array (
    'id' => '3',
    'version' => '1.1.2',
    'release_date' => '2026-02-19',
    'description' => 'Perbaikan logika dan tampilan agenda
Perbaikan tampilanjabatan guru di frontend
Penambahan lihat situs di admin
Perbaikan dashboard admin',
    'is_stable' => '0',
    'created_at' => '2026-02-11 12:02:27',
    'updated_at' => '2026-02-19 11:48:56',
  ),
  10 => 
  array (
    'id' => '1',
    'version' => '1.1.1',
    'release_date' => '2026-02-10',
    'description' => 'Implementasi pembobotan nilai dinamis (Formatif/Sumatif).
Fitur impor guru bagi admin.
Ekspansi data profil guru (Identitas, Pendidikan, Karier).
Fitur mandiri pembaruan profil dan password bagi guru.
Modul "Tentang Aplikasi" dan Changelog.
Perbaikan Modul Chat',
    'is_stable' => '0',
    'created_at' => '2026-02-10 08:49:33',
    'updated_at' => '2026-02-19 04:18:33',
  ),
  11 => 
  array (
    'id' => '2',
    'version' => '1.1.0',
    'release_date' => '2026-02-05',
    'description' => 'PWA Compliance & Installability.
Sinkronisasi branding "SIKAP".
Peningkatan keamanan database & migrations.',
    'is_stable' => '0',
    'created_at' => '2026-02-10 08:49:33',
    'updated_at' => '2026-02-10 08:49:33',
  ),
);
