<?php

/**
 * Script untuk generate changelogs_sync.php dari database
 * Jalankan di localhost sebelum generate patch ZIP
 * 
 * Cara menggunakan:
 * 1. Via command line: php app/Database/sync_changelogs_to_file.php
 * 2. Via browser: http://localhost/siakad/sync-changelogs (jika route dibuat)
 */

// Cek apakah dijalankan via CLI atau web
$isCLI = php_sapi_name() === 'cli';

if (!$isCLI) {
    // Jika via web, bootstrap CodeIgniter
    define('FCPATH', __DIR__ . '/../../public/');
    require_once __DIR__ . '/../../vendor/autoload.php';
    
    $paths = new \Config\Paths();
    $app = new \CodeIgniter\CodeIgniter($paths);
    $app->initialize();
} else {
    // Jika via CLI, bootstrap sederhana
    require __DIR__ . '/../../vendor/autoload.php';
    
    // Set paths
    define('APPPATH', __DIR__ . '/../');
    define('ROOTPATH', __DIR__ . '/../../');
    define('FCPATH', ROOTPATH . 'public/');
    define('WRITEPATH', ROOTPATH . 'writable/');
}

try {
    // Get database connection
    $db = \Config\Database::connect();
    
    // Get all changelogs, ordered by release_date DESC
    $changelogs = $db->table('changelogs')
        ->orderBy('release_date', 'DESC')
        ->get()
        ->getResultArray();
    
    if (empty($changelogs)) {
        $message = "⚠️  Warning: Tidak ada changelog di database!\n";
        if ($isCLI) {
            echo $message;
        } else {
            echo "<pre>{$message}</pre>";
        }
        exit(1);
    }
    
    // Generate PHP array code
    $output = "<?php\n\n";
    $output .= "// This file is automatically generated for synchronization between development and production.\n";
    $output .= "// Created: " . date('Y-m-d H:i:s') . "\n";
    $output .= "// Total changelogs: " . count($changelogs) . "\n\n";
    $output .= "return " . var_export($changelogs, true) . ";\n";
    
    // Write to file
    $syncFile = __DIR__ . '/changelogs_sync.php';
    $result = file_put_contents($syncFile, $output);
    
    if ($result === false) {
        throw new \Exception("Gagal menulis file: {$syncFile}");
    }
    
    // Success message
    $message = "✅ Changelog sync file berhasil diupdate!\n";
    $message .= "📁 File: {$syncFile}\n";
    $message .= "📊 Total changelogs: " . count($changelogs) . "\n";
    $message .= "📅 Versi terbaru: " . ($changelogs[0]['version'] ?? 'N/A') . "\n";
    $message .= "\n";
    $message .= "Langkah selanjutnya:\n";
    $message .= "1. Generate patch ZIP di halaman Updater\n";
    $message .= "2. Upload ke production\n";
    $message .= "3. Jalankan 'Update File' dan 'Jalankan Migrasi'\n";
    
    if ($isCLI) {
        echo $message;
    } else {
        echo "<pre>{$message}</pre>";
    }
    
    exit(0);
    
} catch (\Throwable $e) {
    $error = "❌ Error: " . $e->getMessage() . "\n";
    $error .= "File: " . $e->getFile() . "\n";
    $error .= "Line: " . $e->getLine() . "\n";
    
    if ($isCLI) {
        echo $error;
    } else {
        echo "<pre>{$error}</pre>";
    }
    
    exit(1);
}
