<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cetak Modul Ajar - <?= esc($subject['name']) ?></title>
    <style>
        @page {
            size: portrait;
            margin: 1.5cm;
        }
        body {
            font-family: 'Times New Roman', Times, serif, Arial, sans-serif;
            font-size: 12pt;
            line-height: 1.4;
            color: #000;
        }
        .text-center { text-align: center; }
        .fw-bold { font-weight: bold; }
        
        .footer-table {
            width: 100%;
            margin-top: 60px;
        }
        .footer-table td {
            width: 50%;
            text-align: center;
        }
        .signature-space {
            height: 80px;
        }
        
        @media print {
            .no-print { display: none; }
            body { margin: 0; }
        }

        /* Adjusting standard tags generated by AI/CKEditor */
        table {
            border-collapse: collapse;
            width: 100%;
            margin-bottom: 1em;
        }
        table, th, td {
            border: 1px solid black;
        }
        
        .footer-table, .footer-table th, .footer-table td {
            border: none !important;
        }
        th, td {
            padding: 5px;
        }
        h1, h2, h3, h4 {
            margin-top: 1em;
            margin-bottom: 0.5em;
        }
    </style>
</head>
<body onload="window.print()">
    <div class="no-print" style="background: #f8f9fa; padding: 10px; border-bottom: 1px solid #ddd; margin-bottom: 20px;">
        <button onclick="window.print()" style="padding: 5px 15px; cursor: pointer;">🖨️ Cetak Sekarang</button>
        <button onclick="window.close()" style="padding: 5px 15px; cursor: pointer; margin-left: 10px;">❌ Tutup</button>
    </div>

    <!-- Generated Content -->
    <div class="content-wrapper">
        <?= $modul['content'] ?>
    </div>

    <table class="footer-table">
        <tr>
            <td>
                Mengetahui,<br>
                Kepala Sekolah
                <div class="signature-space"></div>
                <strong><?= esc($school['headmaster'] ?? '-') ?></strong><br>
                NIP. <?= esc($school['principal_nip'] ?? '-') ?>
            </td>
            <td>
                <?= esc($school['city_regency'] ?? 'Indramayu') ?>, <?= date('d F Y') ?><br>
                Guru Kelas/Mapel
                <div class="signature-space"></div>
                <strong><?= esc($teacher['name'] ?? '-') ?></strong><br>
                NIP. <?= esc($teacher['nip'] ?? '-') ?>
            </td>
        </tr>
    </table>
</body>
</html>
