<?php

namespace App\Controllers\Admin;

use App\Controllers\BaseController;
use App\Models\ChangelogModel;

class Changelogs extends BaseController
{
    protected $changelogModel;

    public function __construct()
    {
        // Restriction: Only accessible from localhost (Developer privilege)
        $host = $_SERVER['HTTP_HOST'] ?? '';
        $isLocalhost = (
            $host === 'localhost' || 
            strpos($host, 'localhost:') === 0 || 
            $host === '127.0.0.1' || 
            strpos($host, '127.0.0.1:') === 0
        );
        
        if (!$isLocalhost) {
            header('HTTP/1.1 403 Forbidden');
            exit('Access Denied: This feature is only available in the development environment (localhost).');
        }
        $this->changelogModel = new ChangelogModel();
    }

    public function index()
    {
        $data = [
            'title' => 'Manajemen Changelog',
            'changelogs' => $this->changelogModel->orderBy('release_date', 'DESC')->orderBy('version', 'DESC')->findAll()
        ];

        return view('admin/changelogs/index', $data);
    }

    public function create()
    {
        return view('admin/changelogs/form', [
            'title' => 'Tambah Changelog',
            'changelog' => null
        ]);
    }

    public function edit($id)
    {
        $changelog = $this->changelogModel->find($id);
        if (!$changelog) {
            return redirect()->to('/admin/changelogs')->with('error', 'Data tidak ditemukan.');
        }

        return view('admin/changelogs/form', [
            'title' => 'Edit Changelog',
            'changelog' => $changelog
        ]);
    }

    public function save()
    {
        $id = $this->request->getPost('id');
        $data = [
            'version' => $this->request->getPost('version'),
            'release_date' => $this->request->getPost('release_date'),
            'description' => $this->request->getPost('description'),
            'is_stable' => $this->request->getPost('is_stable') ? 1 : 0,
        ];

        if ($id) {
            $this->changelogModel->update($id, $data);
            $msg = 'Changelog berhasil diperbarui.';
        } else {
            $this->changelogModel->insert($data);
            $msg = 'Changelog berhasil ditambahkan.';
        }

        $this->syncToDataFile();

        return redirect()->to('/admin/changelogs')->with('success', $msg);
    }

    public function delete($id)
    {
        $this->changelogModel->delete($id);
        $this->syncToDataFile();
        return redirect()->to('/admin/changelogs')->with('success', 'Changelog berhasil dihapus.');
    }

    /**
     * Export all changelog data to a PHP file for staging/production sync.
     */
    private function syncToDataFile()
    {
        $allLogs = $this->changelogModel->orderBy('release_date', 'DESC')->orderBy('version', 'DESC')->findAll();
        $filePath = APPPATH . 'Database/changelogs_sync.php';

        $exportData = "<?php\n\n";
        $exportData .= "// This file is automatically generated for synchronization between development and production.\n";
        $exportData .= "// Created: " . date('Y-m-d H:i:s') . "\n\n";
        $exportData .= "return " . var_export($allLogs, true) . ";\n";

        file_put_contents($filePath, $exportData);
    }
}
